# Use an official Node.js image as the base image
FROM node:14-alpine as build

WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install

# Copy the rest of the frontend application code to the container
COPY frontend/ .

# Build the frontend application
RUN npm run build

CMD ["serve","-d","./dist","-p","8006"]